/*
  # Add tags column to artworks table

  ## Summary
  Adds an AI-generated tags field to the artworks table to support the
  auto-tagging and art style detection feature.

  ## Changes
  - `artworks` table: new `tags` column (TEXT, default empty string)
    Stores comma-separated tags generated by the CLIP model and ColorThief,
    including art style labels and dominant color descriptions.

  ## Notes
  - Uses TEXT type (comma-separated) for broad compatibility
  - Default is empty string so existing rows are unaffected
  - No RLS changes needed; artworks table policies are inherited
*/

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'artworks' AND column_name = 'tags'
  ) THEN
    ALTER TABLE artworks ADD COLUMN tags TEXT DEFAULT '';
  END IF;
END $$;
